# welcome to numpy tutorial

In [1]:
import numpy as np
myarr = np.array([[2,23,4,1]])
print(int(myarr[0,2])) #retrive number from the given index

4


In [2]:
myarr[0,1] = 45 #change the number on a given index

In [3]:
myarr.shape #tell the no. of rows and cols in an array

(1, 4)

In [4]:
zeros = np.zeros((2,5)) #creates a zero array of the given size

In [5]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
arg = np.arange(15) #prints values upto a given range

In [7]:
arg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
lspace = np.linspace(1,3,3) #creates and prints an array of equallay spaced numbers

In [9]:
lspace

array([1., 2., 3.])

In [10]:
a = np.empty((4,3)) #creates an  array of a new shape 

In [11]:
a

array([[8.60688992e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.42413554e-306, 7.99960939e+169],
       [1.23162529e+165, 8.77869444e-071, 6.29431901e-066],
       [4.50654085e-033, 9.90525836e+164, 1.46474586e-075]])

In [12]:
emplike = np.empty_like(a) #creates an array of the shape of a given array

In [13]:
emplike

array([[8.60688992e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.42413554e-306, 7.99960939e+169],
       [1.23162529e+165, 8.77869444e-071, 6.29431901e-066],
       [4.50654085e-033, 9.90525836e+164, 1.46474586e-075]])

In [14]:
ide = np.identity(3) #creates an identity matrix

In [15]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
rsp = arg.reshape(3,5) #changes the shape of an array accoding to the given rows cols

In [17]:
rsp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
rsp.ravel() #reforms an array to its original after reshape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x) #converted x to numpy array

In [20]:
ar.sum(axis=0) #sum all the elements of every column

array([12,  8,  9])

In [21]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [22]:
for y in ar.flat:
    print(y) #flat acceses every object y is a variable to access single object

1
2
3
4
5
6
7
1
0


In [23]:
ar.ndim #dimension

2

In [24]:
ar.nbytes #total bytes used

72

In [25]:
print(ar.argmax()) #index at which max value is situated
print(ar.argmin()) #index at which min value is situated

6
8


In [26]:
z = np.array([1,2,3,4,53,2,1])
z.argsort()  #accending order of numbers through index

array([0, 6, 5, 1, 2, 3, 4])

In [27]:
sys = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
sys2 = np.array([[ 5,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

sysa = sys + sys2 
sysm = sys * sys2 
print(sysm)
print(sysa)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
[[ 5  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [28]:
np.sqrt(sys) #undroot

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [29]:
sys*sys2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [30]:
sys.sum()

np.int64(105)

In [31]:
sys.min()

np.int64(0)

In [32]:
sys.max()

np.int64(14)

In [33]:
np.where(arg>2) #gives numbers greater than 2

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [34]:
np.count_nonzero(sys) #counts non zero elements

14

In [35]:
np.nonzero(sys) #gives the 2d index of non zeros

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [36]:
import sys #itemsize for no of bytes per elment
sys2.itemsize *sys2.size #size for no. of elements

120

In [37]:
sys2.tolist() #gives a numpy list

[[5, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]